blank_issues_enabled: false
contact_links:
  - name: ğŸ¤ GitHub Community Support
    url: https://github.com/fonoster/fonoster/discussions
    about: Please ask and answer questions here.
  - name: ğŸ’¬ Discord Community
    url: https://discord.gg/4QWgSz4hTC
    about: Join our Discord community here.